### ISSUE TITLE
6 test cases fail in `main`

### ISSUE THREAD

**Issue by AArnott** [eiriktsarpalis/typeshape-csharp#16]
3 CborTests and 3 XmlTests fail at the tip of main (99068c0e962dc3221806806b81e5d6320328ef14).

**Comment by eiriktsarpalis** [comment]
Which ones? I don't see something failing in CI.

**Comment by AArnott** [comment]
![image](https://github.com/user-attachments/assets/a65aaf0c-ab9e-4f39-8311-d192b53737a5)

**Comment by eiriktsarpalis** [comment]
Interesting. Guessing it's an issue with your TZ specifically. Do you know what inputs are causing this specifically?

**Comment by AArnott** [comment]
What is my "TZ"? Oh! time zone perhaps? Have you tried running these in Visual Studio? Just the first of these fails in 7 out of 447 test cases.
The first failing test case is:

> TypeShape.Tests.CborTests_Reflection.Roundtrip_Value<DateTime>(testCase: TestCase { Value = 12/31/9999 11:59:59 PM, AdditionalValues = System.DateTime[], ExpectedEncoding = , IsStack = False, IsLossyRoundtrip = False, HasRefConstructorParameters = False, HasOutConstructorParameters = False, UsesSpanConstructor = False, Type = System.DateTime, IsNullable = False, IsEquatable = True, IsTuple = False, IsLongTuple = False, IsMultiDimensionalArray = False, IsAbstract = False }) 

I've tried looking at the test cases but there appears to be several levels of indirection in their generation so I haven't tracked down how these values are originally created. But ya, maybe they work on one time zone and not another.

**Comment by eiriktsarpalis** [comment]
If I were to make a guess, it's because the test data is using `DateTime.MaxValue` which fails to roundtrip when the local timezone has a negative offset.
