### ISSUE TITLE
Minimum .NET 8 SDK? Source generators does not seem to work with .NET 8.0.1x SDK versions

### ISSUE THREAD

**Issue by mamift** [eiriktsarpalis/typeshape-csharp#19]
Hello

Can you please mention somewhere (like in the README) what minimum SDK version is required.

I'm trying this library out following the [instructions here](https://eiriktsarpalis.wordpress.com/2024/10/22/source-generators-for-free/), but the source generators do not run at all using .NET 8 SDK 8.0.110 which is kind of a bummer because I'm using VS 2022 17.10 LTSC which doesn't use the latest SDK version (which I think is 8.0.4x)

**Comment by eiriktsarpalis** [comment]
I suspect you might have hit this issue https://github.com/eiriktsarpalis/typeshape-csharp/issues/18. I'll try to push a fix but in the meantime you could try using the latest VS 2022 Preview which is known to work.

**Comment by eiriktsarpalis** [comment]
Can you try again? I just pushed version 0.12.1 which should work with any .NET 8 SDK or Visual Studio version above 17.8.

**Comment by mamift** [comment]
Thanks, it works fine with 17.10
