### ISSUE TITLE
How to implement VisitEnum when serializing as the ordinal value?

### ISSUE THREAD

**Issue by AArnott** [eiriktsarpalis/typeshape-csharp#28]
In MessagePack-CSharp, the default way to serialize an enum is by its ordinal value. But I can't figure out how to emulate that.

I have this:

```cs
public override object? VisitEnum<TEnum, TUnderlying>(IEnumTypeShape<TEnum, TUnderlying> enumShape, object? state = null)
{
    if (typeof(TUnderlying) == typeof(int))
    {
        return new EnumInt32Formatter<TEnum>();
    }
    else
    {
        throw new NotSupportedException();
    }
}
```

And this:

```cs
private sealed class EnumInt32Formatter<T> : IMessagePackFormatter<T>
    where T : struct, Enum
{
    public T Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options) => (T)reader.ReadInt32();
    public void Serialize(ref MessagePackWriter writer, T value, MessagePackSerializerOptions options) => writer.Write((int)value);
}
```

But C# doesn't like the cast of `int` to `T`. I feel like we need `IEnumTypeShape` to provide generic delegates that can do the cast.

Ideally, I could avoid having to implement a special formatter for each underlying type, but I'm not sure that will be possible, given I need to make a call to some `Read*` method depending on what that underlying type is.
But right now, even for one special purpose formatter, I can't figure out how to get it to compile.

**Comment by eiriktsarpalis** [comment]
Doesn't `(T)(object)reader.Int32();` and `(int)(object)value` work? The JIT should be able to optimize those:

https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQEwEYCwAUJgAwAEmuAdAEoCmAZgDZ0DGCUA9jANxGlkAygAsIAJwAOAGQjBaAVxgcwdPoSJEA2gCkoCAOJ0YdMVFYAKBAE8JdTg3MAhWABNYAcwBiTCO5QBKfwBdIhQ6CBYXCmwyAFEYeTAASSUAZmxPTjFIBAQTAB4AFQA+IjJysgB3YRM6MkKyEDIUBDF5djg4hLAiAG8yisxU+rIAETow0wioAC86c1gEMm7gE38yAF5isnNC/3NOYAArNgR/FZM1CophxaETKGm53bIANwj5OnWtncX9w5O7H87yYnzUAF8gA===

**Comment by AArnott** [comment]
Great. Casting through `(object)` only briefly occurred to me but I dismissed it because of the boxing that I assumed would occur. It's great that the JIT removes it. :)
