### ISSUE TITLE
Generating a witness of an enum type produces a compile error in the source generated code

### ISSUE THREAD

**Issue by AArnott** [eiriktsarpalis/typeshape-csharp#29]
When I add this to the `TypeShape.Tests` project:

```cs
[GenerateShape<MyEnum>]
partial class Witness { }
```

I get this compile error:

>Q:\source\typeshape-csharp\tests\TypeShape.Tests\obj\Debug\net8.0\generated\TypeShape.SourceGenerator\TypeShape.SourceGenerator.TypeShapeIncrementalGenerator\TypeShape.Tests.MsgPackSerializerTests.Witness.MyEnum.g.cs(25,38,25,43): error CS0119: 'int' is a type, which is not valid in the given context

which points to this generated code:

```cs
private global::TypeShape.Abstractions.ITypeShape<global::TypeShape.Tests.MyEnum> Create_MyEnum()
{
    return new global::TypeShape.SourceGenModel.SourceGenEnumTypeShape<global::TypeShape.Tests.MyEnum, int>
    {
        UnderlyingType = Int32, // error on this line
        Provider = this,
    };
}
```

I can workaround it by adding yet another witness explicitly:

```diff
+[GenerateShape<int>]
 [GenerateShape<MyEnum>]
 partial class Witness { }
```

But having to do that seems very tedious. Shouldn't transitive types like this be implicit?

**Comment by eiriktsarpalis** [comment]
Thanks. It would seem like the shape of the underlying type isn't being generated.
