### ISSUE TITLE
Reference Type nullability not working properly

### ISSUE THREAD

**Issue by Tornhoof** [eiriktsarpalis/typeshape-csharp#3]
While I was writing some Breadth-First-Search code (I'll submit a PR when I get this working as another sample). I noticed that Reference Type nullability does not properly work inside list or array. As far as I see, all your test types are of format \<type\>? and not \<type?\> or \<type?\>?

```c#
    public partial class FailingNullability
    {
        [Fact]
        public void HappyCase()
        {
            
        }

        [GenerateShape]
        public partial class Poco
        {
            // fails
            public List<string?> DataList { get; set; } = [];
            // fails
            public string?[] DataArray { get; set; } = [];
            // works
            public List<int?> ValueData { get; set; } = [];
        }
    }
```

Errors are:
```ini
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS8619	Nullability of reference types in value of type 'string?[]' doesn't match target type 'string[]'.			[...]\GenerateShapeProvider.FailingNullability_Poco.g.cs	57	Active	
Error	CS8619	Nullability of reference types in value of type 'List<string>' doesn't match target type 'List<string?>'.	[...]\GenerateShapeProvider.FailingNullability_Poco.g.cs	43	Active	
Error	CS8619	Nullability of reference types in value of type 'List<string>' doesn't match target type 'List<string?>'.	[...]\GenerateShapeProvider.FailingNullability_Poco.g.cs	91	Active	
Error	CS8619	Nullability of reference types in value of type 'List<string?>' doesn't match target type 'List<string>'.	[...]\GenerateShapeProvider.FailingNullability_Poco.g.cs	42	Active	

```

**Comment by eiriktsarpalis** [comment]
Ah yes, nullable type parameters is not something that can be supported. Fixing the error would require including suppressions in the relevant getter and setter delegates. Whether they do include suppressions is governed by this logic

https://github.com/eiriktsarpalis/typeshape-csharp/blob/0cf9a24c174b302d4f9f60fc2fadd8c3aa369070/src/TypeShape.SourceGenerator/SourceFormatter/SourceFormatter.Properties.cs#L22-L34

which would need to be extended to detect nullable type parameters. This can be determined using the [`SymbolEqualityEquality.IncludeNullability`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.symbolequalitycomparer.includenullability?view=roslyn-dotnet-4.7.0) comparer
