### ISSUE TITLE
TS0002 should include a Location to the non-partial declaration

### ISSUE THREAD

**Issue by AArnott** [eiriktsarpalis/typeshape-csharp#36]
The following error:

> TS0002 The type 'MessagePackSerializerTests.ReferencesUnannotatedPoco' has been annotated with GenerateShapeAttribute but it or one of its parent types are not partial.

Is emitted without a location (or at least, the VS Error List presents it as the csproj, line 1). That makes *finding* the guilty code much more tedious than if the diagnostic were emitted with a Location matching the declaration on which the attribute was applied.

**Comment by eiriktsarpalis** [comment]
That's odd, according to the source code this is the only location where this diagnostic is being emitted:

https://github.com/eiriktsarpalis/typeshape-csharp/blob/fcbaf23466f745a37ef2e892b3e660afe5f69d43/src/TypeShape.SourceGenerator/Parser/Parser.cs#L231-L234

It's getting the location from a syntax node which is always populated and valid. Do you have a repro you could share?
