### ISSUE TITLE
PropertyShapeAttribute.Order property is not available at runtime except by Reflection

### ISSUE THREAD

**Issue by AArnott** [eiriktsarpalis/typeshape-csharp#37]
It seems odd to me that the only way to get the arguments passed to the `PropertyShapeAttribute` is by the `IPropertyShape.AttributeProvider` which engages Reflection. It seems if the value prop is to avoid reflection, that the attribute presented by the library should include its own arguments in the source generated data structures.

In general though, I'm curious about this. If reflection is necessary (or allowed) to look at custom attributes on these members, is it even safe for me to rely on in all the environments my code may run in? The reason I ask is I may want to define my own attributes to allow further customization than TypeShape includes via its own attributes.

**Comment by AArnott** [comment]
It looks like `PropertyShapeAttribute.Name` is carried over already into the source generated data structure, and I suppose `Ignore` is implicitly carried over by its presence or lack thereof. But `Order` is left out.

**Comment by AArnott** [comment]
Oh, I see. `Order` is like `Ignore` in that its value isn't present but its effect is applied.

That means I can't use it for determining array indexes for property values and I'll have to write my own attribute. Fair enough, but that re-emphasizes my question about relying on Reflection for this data.

**Comment by eiriktsarpalis** [comment]
> That means I can't use it for determining array indexes for property values and I'll have to write my own attribute.

I'm guessing you need the actual ordinal as specified by the user versus the implicit index you get from the property enumeration? (i.e. doing something like `GetProperties().Select((i,x) => ..)`?)

> Fair enough, but that re-emphasizes my question about relying on Reflection for this data.

I should emphasize that accessing attributes via the `AttributeProvider` properties in the TS APIs is considered safe for NAOT. They are being source generated in a way that guarantees the linker won't ever trim metadata from the underlying members.

**Comment by AArnott** [comment]
> I should emphasize that accessing attributes via the AttributeProvider properties in the TS APIs is considered safe for NAOT. They are being source generated in a way that guarantees the linker won't ever trim metadata from the underlying members.

Great. But I'm having a hard time imagining how that's possible because it looks like ordinary reflection to me:

```cs
AttributeProviderFunc = static () => typeof(global::ObjectsAsArraysTests.Person).GetProperty("LastName", InstanceBindingFlags, null, typeof(string), [], null),
```

> I'm guessing you need the actual ordinal as specified by the user versus the implicit index you get from the property enumeration?

Yes. The user needs to be able to say "this property's value goes into array index 15" even if there are only 10 properties currently defined.

**Comment by eiriktsarpalis** [comment]
> But I'm having a hard time imagining how that's possible because it looks like ordinary reflection to me:

The trimmer recognizes reflection lookup expressions like this one as "literals" and as such knows that it has to preserve metadata for the member.
